[tool.poetry]
name = "cym-semantic-layer"
version = "0.1.0"
description = "Build a semantic layer to allow an agent to interact with a vector database in consistent and robust way."
authors = [
    "Brian Lam <brian@cymbiotika.com>",
]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "cym_semantic_layer"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "semantic_layer"
author = "Cymbiotika"
integrations = ["RAG", "OpenAI"]
tags = ["search", "RAG", "function-calling"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
